### PR TITLE
Fix "default start command" example

### PR DESCRIPTION
**Pull request by michaeldwan**

### CODE REVIEW

**Comment by elbandito** [comment]
@michaeldwan while you're at it, I think this also needs to be updated:
https://github.com/buildpack/docs/blob/master/docs/docs/create-buildpack/make-app-runnable/index.html#L139

**Comment by michaeldwan** [comment]
@elbandito good catch, fixed

**Comment by ameyer-pivotal** [comment]
@michaeldwan We've made some adjustments that make our repo simpler. Unfortunately, it requires redoing this change.

**Comment by jkutner** [comment]
This was fixed elsewhere

**Pull request closed without merging**
